### ISSUE TITLE
SSL errors with mxscript extension v.0.5.3 and Maximo 7.6.0.9

### ISSUE THREAD

**Issue by reedand** [ahmednrana/mxscript#1]
Hi: Just a heads-up I received the following 3 errors attempting to use mxscript with VS Code on macOS Catalina and was unable to get the extension working.

-----------------------

Visual Studio Code Version Info:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (1 day ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Error in fetching data Error 500: nested exception is: java.lang.NullPointerException
-----------------------
Error undefined : request to https://mydomain.com/meaweb/os/MXSCRIPT failed, reason: self signed certificate
undefined
-----------------------
Error undefined : request to https://mydomain.com:9080/meaweb/os/MXSCRIPT failed, reason: write EPROTO 140210699261272:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

undefined

**Comment by ahmednrana** [comment]
Thanks for reporting.
I have updated it to handle self signed certs. Can you please check the updated version from market place?
If you still face the issue, can you share the keys for maxscript from settings.json.
Also, have you created the object structure MXSCRIPT or are you using the default one i.e. MXAPIAUTOSCRIPT

**Comment by reedand** [comment]
Thanks for getting back to me.  Unfortunately I’m still having problems.  I receive the following error:

Error undefined : request to https://192.168.222.128:9080/meaweb/os/MXSCRIPT failed, reason: write EPROTO 140400860783640:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242: undefined

I’m using the MXAPIAUTOSCRIPT OS and the following settings.json

"mxscript.serverSettings.hostname": "192.168.222.128",
"mxscript.serverSettings.httpProtocol": "https",
"mxscript.serverSettings.port": 9080

For "Authentication Type" I have “Internal”,
“Username” - “maxadmin”
I have the correct password configured in the Settings for that account.
"Create Python File For Jython Scripts” is ticked,
"Log Level”- “Debug"
“Object Structure”- “MXAPIAUTOSCRIPT”.

**Comment by ahmednrana** [comment]
I'll look into it. Are you sure about the port 9080. Usually it's used with http for Maximo.

**Comment by ahmednrana** [comment]
I cannot re produce thiss with my environment. Can you help in diagnosing the issue. It will take a few mins.
Please install [insomnia](https://insomnia.rest/download/).
Create a new request in it. 
1. Set the URL to 
https://192.168.222.128:9080/meaweb/os/MXAPIAUTOSCRIPT
2. Set a header for authentication
![image](https://user-images.githubusercontent.com/21101759/82810310-88cbb500-9ea7-11ea-89e5-0d76f63580c0.png)
Format it like 
[USERNAME]:[PASSWORD] in base64

3. Add body as XML
```
<QueryMAXSCRIPT xmlns="http://www.ibm.com/maximo">
  <MAXSCRIPTQuery>
    <AUTOSCRIPT>
      <AUTOSCRIPT operator="=">yourscriptname</AUTOSCRIPT>
    </AUTOSCRIPT>
  </MAXSCRIPTQuery>
</QueryMAXSCRIPT>
```
4. Click Send
5. Can you please send me the Response from the tab **Timeline**

**Comment by ahmednrana** [comment]
Added an option to ignore ssl errors. Enable that and it should work for you
